#!/bin/sh
#

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2



# execute test file

current_branch=`git branch | grep '*' | sed 's/* //'`

if [ "$current_branch" = "master" ]; then
  echo "You are about to commit on master. I will run your tests first..."
  python pytest -v --ignore=data
  if [ $? -eq 0 ]; then
        # tests passed, proceed to prepare commit message
        exit 0
   else
    # some tests failed, prevent from committing broken code on master
    echo "Some tests failed. You are not allowed to commit broken code on master! Aborting the commit."
    echo "Note: you can still commit broken code on the other branches"
    exit 1
  fi
fi